title: title_here # name of the site
author: JoÃ£o Vitor Belmonte Rates # name of site's author
email: jv.belmonterates@gmail.com # email of site's author
url: jvbrates.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Description here

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag


lsi: false
safe: true
source: []
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

